//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArchitectureCeA.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using ArchitectureCeA.Model;
    
    public partial class ArchitectureCeAEntities : DbContext
    {
        public ArchitectureCeAEntities()
            : base("name=ArchitectureCeAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ActionPlan> ActionPlan { get; set; }
        public virtual DbSet<Evaluation> Evaluation { get; set; }
        public virtual DbSet<EvaluationPractice> EvaluationPractice { get; set; }
        public virtual DbSet<Practice> Practice { get; set; }
        public virtual DbSet<PracticeRequirement> PracticeRequirement { get; set; }
        public virtual DbSet<ProcessPerspective> ProcessPerspective { get; set; }


    }
}
