//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArchitectureCeA.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActionPlan
    {
        public int Id { get; set; }
        public Nullable<int> EvaluationPracticeId { get; set; }
        public string ActionPlanDescription { get; set; }
    
        public virtual EvaluationPractice EvaluationPractice { get; set; }
    }
}
