//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArchitectureCeA.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Practice
    {
        public Practice()
        {
            this.EvaluationPractice = new HashSet<EvaluationPractice>();
            this.PracticeRequirement = new HashSet<PracticeRequirement>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> PerspectiveId { get; set; }
    
        public virtual ICollection<EvaluationPractice> EvaluationPractice { get; set; }
        public virtual ProcessPerspective ProcessPerspective { get; set; }
        public virtual ICollection<PracticeRequirement> PracticeRequirement { get; set; }
    }
}
